import Sofa
from parameters import *

"""
EVERYTHING IN STANDARD UNITS AND MULTIPLICATORS = METERS, KG, SECONDS...

DO NOT TO USE millimeters
"""


def createScene(rootNode):
    
    rootNode.findData('dt').value=lrDT_value
    rootNode.findData('gravity').value='0 0 -9.81'
    rootNode.addObject('RequiredPlugin', pluginName='SoftRobots')
    rootNode.addObject('VisualStyle', displayFlags='showCollision showVisualModels showBehaviorModels showForceFields showInteractionForceFields')
    rootNode.addObject('AsynchroThreadedAnimationLoop', name='ATAL', listening=1, hrDT=hrDT_value, lrDT=lrDT_value, lowRateNode='lowRate', highRateNode='highRate', useThreadOmni=False, printLog=printATAL)
    
    
    # Low frequency loop
    lowRate = rootNode.addChild('lowRate')
    lowRate.addObject('AsynchroLowRateAnimationLoop', name='ALRAL', proxyHighRateObjectNode='GoalProxy', lowRateObjectNode='BeamNode', printLog=printALRAL)
    lowRate.addObject('AsynchroLowRateConstraintSolver', name='ALRCS', tolerance=1e-6, maxIterations=1, printLog=printALRCS)
    lowRate.addObject('DefaultPipeline', depth=6)
    lowRate.addObject('BruteForceBroadPhase')
    lowRate.addObject('BVHNarrowPhase')
    lowRate.addObject('LocalMinDistance', alarmDistance='0.0', contactDistance='0.005',  angleCone='0.01', coneFactor=0.05)
    lowRate.addObject('DefaultContactManager', response='FrictionContactConstraint')
    
    
    ##### The following lines have been automatically generated by the createProxy() function! Ensure yourself of their exactness #####
    
    # lowRate/GoalProxy
    GoalProxy = lowRate.addChild('GoalProxy')
    GoalProxy.findData('tags').value = LRTag
    GoalProxy.addObject('EulerImplicitSolver', tags=LRTag)
    GoalProxy.addObject('CGLinearSolver', tags=LRTag, iterations=100, tolerance=1e-05, threshold=1e-05)
    GoalProxy.addObject('MechanicalObject', tags='proxy lowRate', name="GoalProxyMO", template="Rigid3", position="0.01 0 0.0035 0 0 0 1")
    GoalProxy.addObject('UncoupledConstraintCorrection', tags=LRTag)
    GoalProxy.addObject('AsynchroStateCopyController', tags=LRTag, name='Client', interlocutorName='Server', template="Rigid3", isServer=0, printLog=0)
    GoalProxy.addObject('RestShapeSpringsForceField', tags=LRTag, stiffness=K, angularStiffness=K, external_rest_shape='/highRate/Omni/OmniMO')
    
    GoalProxyCollision = GoalProxy.addChild('GoalProxyCollision')
    GoalProxyCollision.addObject('MechanicalObject', tags=LRTag, template='Vec3', name="GoalProxyCollisionMO")
    GoalProxyCollision.addObject('SphereCollisionModel', radius="0.002", group="3")
    GoalProxyCollision.addObject('RigidMapping', input='@../GoalProxyMO', output='@GoalProxyCollisionMO')
    
    ##### End of the generation #####
    
    
    
    # lowRate/BeamNode
    BeamNode = lowRate.addChild('BeamNode')
    BeamNode.findData('tags').value='lowRate highRate'
    
    
    # Shore A : 10 and 40 available at lab according to Mario
    # poisson's ratio : ~0.49
    
    # lowRate/BeamNode/Beam
    Beam = BeamNode.addChild('Beam')
    Beam.findData('tags').value=LRTag
    Beam.addObject('EulerImplicitSolver', tags=LRTag)
    Beam.addObject('ShewchukPCGLinearSolver', tags=LRTag, iterations="1", tolerance="1e-5", preconditioners="SparseLDLSolver",use_precond=True, update_step="1", )
    
    # This mesh's dimensions are in mm : 5 x 20 x 100  ie in m : 0.005 x 0.020 x 0.100 equals a VOLUME of 0.00001 m*m*m
    Beam.addObject('RegularGridTopology', tags=LRTag, nx=21, ny="5", nz="5", xmin="-0.050", xmax="0.050", ymin="-0.010", ymax="0.010", zmin="-0.0025", zmax="0.0025")
    Beam.addObject('MechanicalObject', tags='lowRate obstacle', name='BeamMO', template='Vec3')
    
    # Volumic mass of silicon = ~1070kg/m*m*m for a shore 10A sample
    Beam.addObject('UniformMass', tags=LRTag, totalMass=M)
    
    
    Beam.addObject('BoxROI', tags=LRTag, name="boxSoft", box="-0.050 -0.015 -0.005 0.035 0.015 0.005", drawBoxes=True, computeTriangles=False, computeEdges=False)
    Beam.addObject('BoxROI', tags=LRTag, name="boxRigidified", box="0.035 -0.015 -0.005 0.050 0.015 0.005", drawBoxes=True, computeTriangles=False, computeEdges=False)
    
    BeamSoft = Beam.addChild('BeamSoft')
    
    BeamSoft.addObject('HexahedronSetTopologyContainer', tags=LRTag, name="softTopo", hexahedra="@../boxSoft.hexahedraInROI")
    BeamSoft.addObject('HexahedronFEMForceField', tags=LRTag, youngModulus="129000", poissonRatio="0.45")
    # Values for Dragon Skin 10A found on papers on the internet    
    BeamSoft.addObject('BoxROI', tags=LRTag, name="boxFixed", box="-0.050 -0.015 -0.005 -0.035 0.015 0.005", drawBoxes=True)
    BeamSoft.addObject('FixedConstraint', tags=LRTag, indices="@boxFixed.indices")
    
    BeamStiff = Beam.addChild('BeamStiff')
    
    BeamStiff.addObject('HexahedronSetTopologyContainer', tags=LRTag, name="rigidTopo", hexahedra="@../boxRigidified.hexahedraInROI")
    BeamStiff.addObject('HexahedronFEMForceField', tags=LRTag, youngModulus="15000000", poissonRatio="0.3")
    BeamStiff.addObject('BoxROI', tags=LRTag, name="boxOnlyX", box="0.045 -0.015 0.002 0.050 0.015 0.003", drawBoxes=True)
    BeamStiff.addObject('PartialFixedConstraint', tags=LRTag, indices="@boxOnlyX.indices", fixedDirections="0 1 1")
    
    
    Beam.addObject('SparseLDLSolver', tags=LRTag)
    Beam.addObject('LinearSolverConstraintCorrection', tags=LRTag, solverName='SparseLDLSolver')

    
    
    ##### The following lines have been automatically generated by the createProxy() function! Ensure yourself of their exactness #####
    
    # lowRate/Beam/BeamProxy
    BeamProxy = BeamNode.addChild('BeamProxy')
    BeamProxy.findData('tags').value=HRTag
    BeamProxy.addObject('EulerImplicitSolver', tags=HRTag)
    BeamProxy.addObject('ShewchukPCGLinearSolver', tags=HRTag, iterations="1", tolerance="1e-5", preconditioners="SparseLDLSolver",use_precond=True, update_step="1", )
    BeamProxy.addObject('RegularGridTopology', tags=HRTag, nx=21, ny="5", nz="5", xmin="-0.050", xmax="0.050", ymin="-0.010", ymax="0.010", zmin="-0.0025", zmax="0.0025")
    BeamProxy.addObject('MechanicalObject', position='@../Beam/BeamMO.position', velocity='@../Beam/BeamMO.velocity', constraint='@../Beam/BeamMO.constraint', tags='highRate obstacleProxy', name='BeamProxyMO', template='Vec3')
    BeamProxy.addObject('UniformMass', tags=HRTag, totalMass=M)
    BeamProxy.addObject('HexahedronFEMForceField', tags=HRTag, template="Vec3", method='large', poissonRatio=v, youngModulus=E)
    BeamProxy.addObject('SparseLDLSolver', tags=HRTag)
    BeamProxy.addObject('LinearSolverConstraintCorrection', tags=HRTag, solverName='SparseLDLSolver', printLog=1)
    
    ##### End of the generation #####
    
    
    
    
    # High frequency loop
    highRate = rootNode.addChild('highRate')
    highRate.addObject('AsynchroHighRateAnimationLoop', name='AHRAL', highRateObjectNode='Goal', interactiveControl='controlledPoints')
    highRate.addObject('AsynchroHighRateConstraintSolver', name='AHRCS', tolerance=1e-1, maxIterations=1, printLog=printAHRCS)
    
    # highRate/Omni
    Omni = highRate.addChild('Omni')
    #Omni.addObject('OmniDriver', scale=1, positionBase='0 0 0.03 0 0 0 1', orientationTool='0.8 0 0 1', )
    Omni.addObject('OmniDriverEmu', scale=1, positionBase='0 0 0 0 0 0 1', orientationTool='0.8 0 0 1', permanent=1, forceScale=1.0, printLog=0, omniVisu=0, \
        #trajPoints='0.01 0 0.0035 0 0 0 1   0.01 0 -0.005 0 0 0 1   0 0 0.004 0 0 0 1   0 0 -0.01 0 0 0 1',  trajTiming='0 5 8 10', listening=True, handleEventTriggersUpdate=True)
    #trajPoints='0 0 0.0025 0 0 0 1  0 0 0.0025 0 0 0 1   0 0 -0.005 0 0 0 1   0 0 0.001 0 0 0 1   0.006 0 0.0025 0 0 0 1',  trajTiming='0 1 3 5 7', listening=True, handleEventTriggersUpdate=True)
    trajPoints='0 0 0.0025 0 0 0 1     0.008 0 0.0025 0 0 0 1',  trajTiming='0 2', listening=True, handleEventTriggersUpdate=True)
    Omni.addObject('MechanicalObject', name='OmniMO', template="Rigid3", position='0 0 0 0 0 0 1')
    Omni.addObject('MechanicalStateController', template="Rigid3", listening=1, mainDirection='0.0 -0.01 0.0', handleEventTriggersUpdate=1)
    
    
    # /highRate/Goal
    Goal = highRate.addChild('Goal')
    Goal.addObject('EulerImplicitSolver')
    Goal.addObject('CGLinearSolver', iterations=100, tolerance=1e-05, threshold=1e-05)
    # vertical position is 0.0025 initially so we ask for a displacement of 0.001m
    Goal.addObject('MechanicalObject', tags=HRTag, name="GoalMO", template="Rigid3", position="0.01 0 0.0035 0 0 0 1")
    Goal.addObject('UncoupledConstraintCorrection', tags=HRTag)
    #Goal.addObject('AsynchroVMechanismsForceFeedback', useRealCompliance=0, reallyApplyForces=1, attachedIndex=0, activate=1, forceCoef=1.0)
    Goal.addObject('AsynchroStateCopyController', name='Server', interlocutorName='Client', template="Rigid3", isServer=1, listening=1, printLog=0)
    Goal.addObject('RestShapeSpringsForceField', stiffness=K, angularStiffness=K, external_rest_shape='/highRate/Omni/OmniMO')
    
    # /highRate/Goal/GoalCollision
    GoalCollision = Goal.addChild('GoalCollision')
    GoalCollision.addObject('MechanicalObject', template='Vec3', name="GoalCollisionMO")
    GoalCollision.addObject('SphereCollisionModel', radius="0.002", group="3")
    GoalCollision.addObject('RigidMapping', input='@../GoalMO', output='@GoalCollisionMO')
    
    
    # /lowRate/BeamNode/Beam/controlledPoints
    controlledPoints = Beam.addChild('controlledPoints')
    controlledPoints.addObject('MechanicalObject', template="Vec3", position="0 0 0.0025   0.045 0.005 0   0.045 -0.0040 0   -0.045 0.005 0   -0.045 -0.005 0  0.05 0.0 0")
    controlledPoints.addObject('PositionEffectorGS', indices=0, effectorGoal="@/highRate/Goal/GoalCollision/GoalCollisionMO.position")
    controlledPoints.addObject('CableActuatorGS', index=5, pullPoint="0.30 0.0 0", maxPositiveDisp=0.25, maxNegativeDisp=0.25, numberOfEffector='1')
    controlledPoints.addObject('BoxROI', box="-0.01 -0.01 -0.01 0.01 0.01 0.01", drawBoxes=True)
    controlledPoints.addObject('ConstantForceField', points='@[-1].indices', force="0 0 -0.04", arrowSizeCoef=0.002, printLog=1)
    controlledPoints.addObject('BarycentricMapping', mapForces=1, mapMasses=0)
    
    highRate.addObject('InteractiveControl', name="Network Interactive Control Mot A", address="127.0.0.1", port="1995", motorIndex="1", mode="3", listening=1, setpoint='@/lowRate/BeamNode/Beam/controlledPoints/QPInverseProblem.setpoint')  # Set listening to true  for HF computation
    
    #<InteractiveControl name="Network Interactive Control Mot A", address="169.254.8.220", motorIndex="0", mode="0", setpoint="@cable0.setpoint", /> -->
    
